<template>     <ComArticle :meta="meta" :demo="demo ? demo : undefined">         <section class="article-core art-ComponentMenu">             <header class="art-header">                 <h1>{{meta.title}}</h1>                 <p>菜单</p>
             </header>             <div class="art-demo">                          </div>             <div class="art-spec">             <h2>Menu</h2>
<p>菜单
Menu
SubMenu
MenuIcon
MenuItem
MenuItemGroup</p>
<h3>属性</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>类型</th>
<th>默认值</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>direction</td>
<td>string</td>
<td>horizontal</td>
<td>菜单渲染方向，可选值：horizontal,vertical</td>
</tr>
<tr>
<td>value</td>
<td>string | { active: string; opened: [ string ] }</td>
<td></td>
<td><strong>可使用<code>v-model</code>方式进行值传递和更新；</strong><br>传递<code>string</code>类型值时，激活<code>sign</code>值一致的<code>MenuItem</code>，当发生用户事件导致<code>MenuItem</code>激活时，会更新<code>value</code>值为激活<code>MenuItem</code>的<code>sign</code>值；<br>传递<code>object</code>类型值时，对象可包含属性：active,opened；<br><code>active</code>接受<code>string</code>类型值，当其值不为空时，将激活<code>sign</code>值一致的<code>MenuItem</code>，当发生用户事件导致<code>MenuItem</code>激活时，会更新<code>value.active</code>值为激活<code>MenuItem</code>的<code>sign</code>值；<br><code>opened</code>接受项目类型为<code>string</code>类型的<code>数组</code>，当其值不为空时，将打开<code>sign</code>值包含在其中的<code>SubMenu</code>，并关闭<code>sign</code>值不包含在其中的<code>SubMenu</code>；当发生用户事件导致<code>SubMenu</code>打开/关闭时，会同步更新<code>value.opened</code>值为已经打开的<code>SubMenu</code>的<code>sign</code>值的集合；</td>
</tr>
<tr>
<td>collapse</td>
<td>boolean</td>
<td>false</td>
<td>设置折叠菜单，仅在<code>direction</code>为<code>vertical</code>时有效</td>
</tr>
<tr>
<td>trigger</td>
<td>string</td>
<td>hover</td>
<td>设置打开子菜单的事件触发方式，可选值：click,hover</td>
</tr>
</tbody>
</table>
<h3>事件</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>input(value)</td>
<td><code>v-model</code>的<code>input</code>事件，传递<code>value</code>值</td>
</tr>
</tbody>
</table>
<h2>SubMenu</h2>
<p>子菜单</p>
<h3>属性</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>类型</th>
<th>默认值</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>sign</td>
<td>string</td>
<td></td>
<td>设置签名，其值应在父<code>Menu</code>组件中保持唯一</td>
</tr>
<tr>
<td>trigger</td>
<td>string</td>
<td></td>
<td>设置展开菜单项的事件触发方式，可选值：click,hover；<br>当不设置值时，默认会从父<code>Menu</code>组件的<code>trigger</code>值中获取；</td>
</tr>
<tr>
<td>disabled</td>
<td>boolean</td>
<td>false</td>
<td>禁用子菜单，禁用后无法通过用户事件(click/hover)打开和关闭，但可以通过调用父<code>Menu</code>组件实例提供的方法（open/close）或者设置父<code>Menu</code>组件的<code>value</code>值这两种方式进行子菜单的打开和关闭</td>
</tr>
</tbody>
</table>
<h2>MenuItem</h2>
<p>菜单项</p>
<table>
<thead>
<tr>
<th>名称</th>
<th>类型</th>
<th>默认值</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>sign</td>
<td>string</td>
<td></td>
<td>设置签名，其值应在父<code>Menu</code>组件中保持唯一</td>
</tr>
</tbody>
</table>
             </div>         </section>     </ComArticle> </template>  <script> /* eslint-disable */ import ComArticle from '../../../components/ComArticle';   export default {     name: 'ComponentMenu',     data() {         return {             name: 'ComponentMenu',             meta: {"category":"Component","order":"1","type":"Navigation","title":"Menu","subtitle":"菜单"},             demo:null         }     },     components:{         ComArticle,                       } } </script> 