<template>     <ComArticle :meta="meta" :demo="demo ? demo : undefined">         <section class="article-core art-ComponentMenu">             <header class="art-header">                 <h1>{{meta.title}}</h1>                 <p>菜单</p>
             </header>             <div class="art-demo">                              <Demo :data="demo[0]">                                          <ComponentMenuPlacement></ComponentMenuPlacement>                                      </Demo>                          </div>             <div class="art-spec">             <h2>Menu</h2>
<p>菜单
Menu
SubMenu
MenuItem
MenuItemGroup</p>
<h3>属性</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>类型</th>
<th>默认值</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>direction</td>
<td>string</td>
<td>horizontal</td>
<td>菜单渲染方向，可选值：horizontal,vertical</td>
</tr>
<tr>
<td>value</td>
<td>string | { active: string; opened: [ string ] }</td>
<td></td>
<td><strong>可使用<code>v-model</code>方式进行值传递和更新；</strong><br>传递<code>string</code>类型值时，激活<code>sign</code>值一致的<code>MenuItem</code>，当发生用户事件导致<code>MenuItem</code>激活时，会更新<code>value</code>值为激活<code>MenuItem</code>的<code>sign</code>值；<br>传递<code>object</code>类型值时，对象可包含属性：active,opened；<br><code>active</code>接受<code>string</code>类型值，当其值不为空时，将激活<code>sign</code>值一致的<code>MenuItem</code>，当发生用户事件导致<code>MenuItem</code>激活时，会更新<code>value.active</code>值为激活<code>MenuItem</code>的<code>sign</code>值；<br><code>opened</code>接受项目类型为<code>string</code>类型的<code>数组</code>，当其值不为空时，将打开<code>sign</code>值包含在其中的<code>SubMenu</code>，并关闭<code>sign</code>值不包含在其中的<code>SubMenu</code>；当发生用户事件导致<code>SubMenu</code>打开/关闭时，会同步更新<code>value.opened</code>值为已经打开的<code>SubMenu</code>的<code>sign</code>值的集合；</td>
</tr>
<tr>
<td>collapsed</td>
<td>boolean</td>
<td>false</td>
<td>折叠菜单，仅当<code>direction</code>等于<code>vertical</code>时有效</td>
</tr>
<tr>
<td>trigger</td>
<td>string</td>
<td>hover</td>
<td>设置打开子菜单的事件触发方式，可选值：click,hover；<br>当<code>direction</code>等于<code>vertical</code>且<code>collapsed</code>等于<code>false</code>时此项配置无效，<code>SubMenu</code>将一直以<code>click</code>方式打开</td>
</tr>
<tr>
<td>router</td>
<td>boolean</td>
<td>false</td>
<td>设置子组件<code>MenuItem</code>以vue-router模式跳转</td>
</tr>
<tr>
<td>router-replace</td>
<td>boolean</td>
<td>false</td>
<td>设置router以replace方式调用，仅在<code>router</code>值为真时有效</td>
</tr>
<tr>
<td>align</td>
<td>string</td>
<td>left</td>
<td>设置子组件<code>MenuItem</code>对齐方式</td>
</tr>
<tr>
<td>placement</td>
<td>string</td>
<td>auto</td>
<td>设置子组件<code>SubMenu</code>弹出框打开位置，可选值：auto,top,left,right,bottom；</td>
</tr>
</tbody>
</table>
<h3>事件</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>click(sign)</td>
<td>子组件<code>MneuItem</code>单击时触发，传递该<code>MenuItem</code>的<code>sign</code>值</td>
</tr>
<tr>
<td>input(value)</td>
<td><code>v-model</code>的<code>input</code>事件，传递<code>value</code>值</td>
</tr>
<tr>
<td>open(sign)</td>
<td>子组件<code>SubMenu</code>打开时触发，传递该<code>SubMenu</code>的<code>sign</code>值，此事件仅在用户事件发生时触发，手动调用<code>Menu</code>组件的<code>open</code>方法时不进行触发</td>
</tr>
<tr>
<td>close(sign)</td>
<td>子组件<code>SubMenu</code>关闭时触发，传递该<code>SubMenu</code>的<code>sign</code>值，此事件仅在用户事件发生时触发，手动调用<code>Menu</code>组件的<code>close</code>方法时不进行触发</td>
</tr>
</tbody>
</table>
<h3>方法</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>open(sign)</td>
<td>打开<code>sign</code>值对应的<code>SubMenu</code>子组件</td>
</tr>
<tr>
<td>close(sign)</td>
<td>关闭<code>sign</code>值对应的<code>SubMenu</code>子组件</td>
</tr>
</tbody>
</table>
<h2>SubMenu</h2>
<p>子菜单</p>
<h3>属性</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>类型</th>
<th>默认值</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>sign</td>
<td>string</td>
<td></td>
<td>设置签名，其值应在父<code>Menu</code>组件中保持唯一</td>
</tr>
<tr>
<td>title</td>
<td>string</td>
<td></td>
<td>设置标题</td>
</tr>
<tr>
<td>trigger</td>
<td>string</td>
<td></td>
<td>设置展开菜单项的事件触发方式，可选值：click,hover；<br>当不设置值时，默认会从父<code>Menu</code>组件的<code>trigger</code>值中获取；</td>
</tr>
<tr>
<td>disabled</td>
<td>boolean</td>
<td>false</td>
<td>禁用子菜单，禁用后无法通过用户事件(click/hover)打开和关闭，但可以通过调用父<code>Menu</code>组件实例提供的方法（open/close）或者设置父<code>Menu</code>组件的<code>value</code>值这两种方式进行子菜单的打开和关闭</td>
</tr>
<tr>
<td>router</td>
<td>boolean</td>
<td><code>Menu.router</code></td>
<td>设置以vue-router模式跳转，默认值取父组件<code>Menu</code>的<code>router</code>属性值</td>
</tr>
<tr>
<td>to</td>
<td>string</td>
<td></td>
<td>设置跳转链接，<code>router</code>值为真时，作用同<code>router-link</code>的<code>to</code>属性，否则作用同<code>a</code>标签的<code>href</code>属性</td>
</tr>
<tr>
<td>router-replace</td>
<td>boolean</td>
<td><code>Menu.router-replace</code></td>
<td>设置router以replace方式调用，仅在<code>router</code>值为真时有效</td>
</tr>
<tr>
<td>target</td>
<td>string</td>
<td></td>
<td>设置跳转目标，作用同<code>a</code>标签的<code>target</code>属性，仅当<code>router</code>值不为真时有效</td>
</tr>
<tr>
<td>placement</td>
<td>string</td>
<td><code>Menu.placement</code></td>
<td>设置<code>SubMenu</code>弹出框打开位置，可选值：auto,top,left,right,bottom；当设置为<code>auto</code>值时，框架会自动设置位置，规则是：<br>父<code>Menu</code>组件<code>direction</code>等于<code>horizontal</code>时，其值为<code>bottom</code>；<br>父<code>Menu</code>组件<code>direction</code>等于<code>vertical</code>时，其值为<code>right</code>；</td>
</tr>
<tr>
<td>align</td>
<td>string</td>
<td><code>Menu.align</code></td>
<td>设置子组件<code>MenuItem</code>对齐方式，默认值取父组件<code>Menu</code>的<code>align</code>属性值</td>
</tr>
</tbody>
</table>
<h3>Slot</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>icon</td>
<td>图标插槽</td>
</tr>
</tbody>
</table>
<h2>MenuItem</h2>
<p>菜单项</p>
<h3>属性</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>类型</th>
<th>默认值</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>sign</td>
<td>string</td>
<td></td>
<td>设置签名，其值应在父<code>Menu</code>组件中保持唯一</td>
</tr>
<tr>
<td>title</td>
<td>string</td>
<td></td>
<td>设置标题</td>
</tr>
<tr>
<td>to</td>
<td>string</td>
<td></td>
<td>设置跳转链接，<code>router</code>值为真时，作用同<code>router-link</code>的<code>to</code>属性，否则作用同<code>a</code>标签的<code>href</code>属性</td>
</tr>
<tr>
<td>target</td>
<td>string</td>
<td></td>
<td>设置跳转目标，作用同<code>a</code>标签的<code>target</code>属性</td>
</tr>
<tr>
<td>router</td>
<td>boolean</td>
<td><code>SubMenu.router</code></td>
<td>设置以vue-router模式跳转，默认值取父组件<code>SubMenu</code>的<code>router</code>属性值，此值为<code>true</code>时，请务必设置<code>to</code>属性</td>
</tr>
<tr>
<td>router-replace</td>
<td>boolean</td>
<td><code>SubMenu.router-replace</code></td>
<td>设置router以replace方式调用，仅在<code>router</code>值为真时有效</td>
</tr>
<tr>
<td>align</td>
<td>string</td>
<td><code>SubMenu.align</code></td>
<td>设置对齐方式，默认值取父组件<code>SubMenu</code>的<code>align</code>属性值</td>
</tr>
</tbody>
</table>
<h3>Slot</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>icon</td>
<td>图标插槽</td>
</tr>
</tbody>
</table>
             </div>         </section>     </ComArticle> </template>  <script> /* eslint-disable */ import ComArticle from '../../../components/ComArticle';  import Demo from '../../../components/Demo';   import ComponentMenuPlacement from '../demo/zh-CN/ComponentMenuPlacement.vue';  export default {     name: 'ComponentMenu',     data() {         return {             name: 'ComponentMenu',             meta: {"category":"Component","order":"1","type":"Navigation","title":"Menu","subtitle":"菜单"},             demo: [{"path":"D:\\MyConfiguration\\ymy48253\\Documents\\MyProject\\putiui\\docs\\posts\\data\\component\\menu\\demo\\placement.zh-CN.md","exp":"md","dirName":"demo","fileName":"placement.zh-CN","name":"Placement","lang":"zh-CN","orgContent":"| component | order | title |\n|-----------|-------|-------|\n| Menu    | 1     | 子菜单打开方向  |\n\n[comment]: meta\n\n[comment]: template:start\n\n```html\n<PtMenu>\n    <PtSubMenu title=\"bottom\" placement=\"bottom\" sign=\"2\">\n        <PtMenuItem sign=\"21\">Menu1</PtMenuItem>\n        <PtMenuItem sign=\"22\">Menu2</PtMenuItem>\n    </PtSubMenu>\n</PtMenu>\n\n<PtMenu>\n    <PtSubMenu title=\"top\" placement=\"top\" sign=\"2\">\n        <PtMenuItem sign=\"21\">Menu1</PtMenuItem>\n        <PtMenuItem sign=\"22\">Menu2</PtMenuItem>\n    </PtSubMenu>\n</PtMenu>\n\n<PtMenu>\n    <PtSubMenu title=\"left\" placement=\"left\" sign=\"2\">\n        <PtMenuItem sign=\"21\">Menu1</PtMenuItem>\n        <PtMenuItem sign=\"22\">Menu2</PtMenuItem>\n    </PtSubMenu>\n</PtMenu>\n\n<PtMenu>\n    <PtSubMenu title=\"right\" placement=\"right\" sign=\"2\">\n        <PtMenuItem sign=\"21\">Menu1</PtMenuItem>\n        <PtMenuItem sign=\"22\">Menu2</PtMenuItem>\n    </PtSubMenu>\n</PtMenu>\n```\n\n[comment]: template:end\n\n\n[comment]: style:start\n\n```css\n\n```\n\n[comment]: style:end\n\n\n[comment]: script:start\n\n```js\nexport default {\n    name: 'demo',\n    data(){\n        return {\n        }\n    }\n}\n```\n\n[comment]: script:end\n","meta":{"component":"Menu","order":"1","title":"子菜单打开方向"},"orgTemplate":"\n\n```html\n<PtMenu>\n    <PtSubMenu title=\"bottom\" placement=\"bottom\" sign=\"2\">\n        <PtMenuItem sign=\"21\">Menu1</PtMenuItem>\n        <PtMenuItem sign=\"22\">Menu2</PtMenuItem>\n    </PtSubMenu>\n</PtMenu>\n\n<PtMenu>\n    <PtSubMenu title=\"top\" placement=\"top\" sign=\"2\">\n        <PtMenuItem sign=\"21\">Menu1</PtMenuItem>\n        <PtMenuItem sign=\"22\">Menu2</PtMenuItem>\n    </PtSubMenu>\n</PtMenu>\n\n<PtMenu>\n    <PtSubMenu title=\"left\" placement=\"left\" sign=\"2\">\n        <PtMenuItem sign=\"21\">Menu1</PtMenuItem>\n        <PtMenuItem sign=\"22\">Menu2</PtMenuItem>\n    </PtSubMenu>\n</PtMenu>\n\n<PtMenu>\n    <PtSubMenu title=\"right\" placement=\"right\" sign=\"2\">\n        <PtMenuItem sign=\"21\">Menu1</PtMenuItem>\n        <PtMenuItem sign=\"22\">Menu2</PtMenuItem>\n    </PtSubMenu>\n</PtMenu>\n```\n\n","template":"\n<PtMenu>\n    <PtSubMenu title=\"bottom\" placement=\"bottom\" sign=\"2\">\n        <PtMenuItem sign=\"21\">Menu1</PtMenuItem>\n        <PtMenuItem sign=\"22\">Menu2</PtMenuItem>\n    </PtSubMenu>\n</PtMenu>\n\n<PtMenu>\n    <PtSubMenu title=\"top\" placement=\"top\" sign=\"2\">\n        <PtMenuItem sign=\"21\">Menu1</PtMenuItem>\n        <PtMenuItem sign=\"22\">Menu2</PtMenuItem>\n    </PtSubMenu>\n</PtMenu>\n\n<PtMenu>\n    <PtSubMenu title=\"left\" placement=\"left\" sign=\"2\">\n        <PtMenuItem sign=\"21\">Menu1</PtMenuItem>\n        <PtMenuItem sign=\"22\">Menu2</PtMenuItem>\n    </PtSubMenu>\n</PtMenu>\n\n<PtMenu>\n    <PtSubMenu title=\"right\" placement=\"right\" sign=\"2\">\n        <PtMenuItem sign=\"21\">Menu1</PtMenuItem>\n        <PtMenuItem sign=\"22\">Menu2</PtMenuItem>\n    </PtSubMenu>\n</PtMenu>\n","orgStyle":"\n\n```css\n\n```\n\n","style":"\n\n","orgScript":"\n\n```js\nexport default {\n    name: 'demo',\n    data(){\n        return {\n        }\n    }\n}\n```\n\n","script":"\nexport default {\n    name: 'demo',\n    data(){\n        return {\n        }\n    }\n}\n"}]         }     },     components:{         ComArticle,                  Demo,                           ComponentMenuPlacement: ComponentMenuPlacement              } } </script> 